TravisCI: Fix exit error of build.sh
Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

diff --git a/zip-creator/travis-ci/0001-TravisCI-Custom-Patches.patch b/zip-creator/travis-ci/0001-TravisCI-Custom-Patches.patch
--- a/zip-creator/travis-ci/0001-TravisCI-Custom-Patches.patch
+++ b/zip-creator/travis-ci/0001-TravisCI-Custom-Patches.patch
@@ -1,33 +1,32 @@
-From 3ff0fa2ffee633a6b5e9e1297414daf2ceeca95c Mon Sep 17 00:00:00 2001
+From 9742d3bc9ebaedc510aafe29a03b95d79e4c8532 Mon Sep 17 00:00:00 2001
 From: Caio Oliveira <caiooliveirafarias0@gmail.com>
-Date: Sun, 10 Jul 2016 17:52:52 -0300
-Subject: [PATCH 1/2] build.sh: Add exit_code because TravisCI
+Date: Wed, 26 Oct 2016 11:59:49 -0200
+Subject: [PATCH 1/2] build.sh: Add exit if any command fail [DO NOT MERGE]
 
-Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>
 ---
- build.sh | 3 ++-
- 1 file changed, 2 insertions(+), 1 deletion(-)
+ build.sh | 4 ++++
+ 1 file changed, 4 insertions(+)
 
 diff --git a/build.sh b/build.sh
-index 3acb77d..72f5bac 100644
+index 55e243c..29ea846 100644
 --- a/build.sh
 +++ b/build.sh
-@@ -119,8 +119,9 @@ else
- 	make -j${build_cpu_usage}${kernel_build_output_enable} ARCH="${ARCH}" CROSS_COMPILE="${kernel_build_ccache}${CROSS_COMPILE}"
- 	if ! [ "$?" == "0" ]
- 	then
-+		exit_code=$?
- 		echo "  | ${color_red}Build Failed! Exiting...${color_stock}"
--		break
-+		exit ${exit_code}
- 	fi
- 	sleep 2
- 	build_time=$(($(date +"%s") - ${start_build_time}))
+@@ -10,6 +10,10 @@
+ # You need to download https://github.com/TeamVee/android_prebuilt_toolchains
+ # Clone in the same folder as the kernel to choose a toolchain and not specify a location
+ 
++# For TravisCI
++# Exit if any command fail
++set -e
++
+ # Device Choice
+ device_choice() {
+ clear
 -- 
-1.9.1
+2.10.1
 
 
-From 2e0a2dee7c23e1848a42e7b1b3adbabbd52958a0 Mon Sep 17 00:00:00 2001
+From a1188e96a4fbfb895e02288edc3fd2f6e3f052fd Mon Sep 17 00:00:00 2001
 From: Caio Oliveira <caiooliveirafarias0@gmail.com>
 Date: Mon, 11 Jul 2016 19:41:32 -0300
 Subject: [PATCH 2/2] mkcompile_h: Add custom TravisCI Kernel Version [DO NOT
@@ -54,5 +53,5 @@ index f221ddf..2bb7309 100755
    echo \#define LINUX_COMPILER \"`$CC -v 2>&1 | tail -n 1`\"
  ) > .tmpcompile
 -- 
-1.9.1
+2.10.1
 
